# netlify.toml
[build]
  publish = "public"          # if you have a static site; otherwise omit
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
